# Generated by Django 4.2.30 on 2026-06-25 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0004_unionmesas_capacidad_personalizada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de inicio de reservas')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de fin de reservas')),
                ('intervalo_minutos', models.PositiveIntegerField(default=30, verbose_name='Intervalo entre reservas (minutos)')),
                ('capacidad_maxima_personas', models.PositiveIntegerField(default=50, verbose_name='Capacidad máxima simultánea')),
            ],
            options={
                'verbose_name': 'Configuración de Reserva',
                'verbose_name_plural': 'Configuraciones de Reservas',
            },
        ),
        migrations.CreateModel(
            name='DiaNoLaborable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha bloqueada')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo (Ej. Feriado, Cierre)')),
            ],
            options={
                'verbose_name': 'Día No Laborable',
                'verbose_name_plural': 'Días No Laborables',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('cliente_telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('cantidad_personas', models.PositiveIntegerField(verbose_name='Cantidad de Personas')),
                ('fecha', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora', models.TimeField(verbose_name='Hora de Reserva')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado o Registrado Por')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.mesa', verbose_name='Mesa Asignada')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
