# Generated by Django 4.2.30 on 2026-06-28 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('reservas', '0002_reserva_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreserva',
            name='tolerancia_no_show_minutos',
            field=models.PositiveIntegerField(default=15, verbose_name='Minutos de espera por no asistencia'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pedido_confirmado',
            field=models.BooleanField(default=False, verbose_name='Pedido confirmado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('FINALIZADA', 'Finalizada'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ReservaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_platos', to='menu.plato', verbose_name='Plato')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Plato de reserva',
                'verbose_name_plural': 'Platos de reserva',
                'unique_together': {('reserva', 'plato')},
            },
        ),
    ]
