# Generated by Django 4.2.30 on 2026-06-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_configuracionreserva_tolerancia_no_show_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreserva',
            name='numero_plin',
            field=models.CharField(blank=True, default='987 654 321', max_length=20, verbose_name='Número Plin'),
        ),
        migrations.AddField(
            model_name='configuracionreserva',
            name='numero_yape',
            field=models.CharField(blank=True, default='987 654 321', max_length=20, verbose_name='Número Yape'),
        ),
        migrations.CreateModel(
            name='ReservaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TARJETA', 'Tarjeta')], max_length=20, verbose_name='Método de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia / N° operación')),
                ('ultimos_digitos_tarjeta', models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos')),
                ('titular_tarjeta', models.CharField(blank=True, max_length=120, null=True, verbose_name='Titular tarjeta')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago de reserva',
                'verbose_name_plural': 'Pagos de reservas',
            },
        ),
    ]
