# Generated by Django 4.2.30 on 2026-06-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0005_lineacomanda_auditoria_cancelacion'),
        ('reservas', '0004_configuracionreserva_numero_plin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente_llego',
            field=models.BooleanField(default=False, verbose_name='Llegada confirmada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_origen', to='comandas.comanda', verbose_name='Comanda generada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_llegada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de llegada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('FINALIZADA', 'Finalizada'), ('NO_ASISTIO', 'No asistió'), ('EN_MESA', 'En mesa')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
