# Generated by Django 4.2.30 on 2026-07-10 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mesas', '0004_unionmesas_capacidad_personalizada'),
        ('clientes', '0001_initial'),
        ('comandas', '0005_lineacomanda_auditoria_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandas_web', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='tipo_pedido',
            field=models.CharField(choices=[('LOCAL', 'Consumo en Local'), ('RECOJO', 'Recojo en Local'), ('DELIVERY', 'Delivery')], default='LOCAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='mesas.mesa'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='mozo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to=settings.AUTH_USER_MODEL),
        ),
    ]
